# Generated by Django 5.2.3 on 2025-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateField(auto_now=True)),
                ('soc_temp', models.FloatField()),
            ],
        ),
    ]
