# Generated by Django 5.2.3 on 2025-06-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='last_try',
        ),
        migrations.AddField(
            model_name='stats',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
