# Generated by Django 5.2.3 on 2025-06-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_remove_stats_last_try_stats_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='soc_temp',
            new_name='cpu_temp',
        ),
        migrations.AddField(
            model_name='stats',
            name='bytes_recv',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='bytes_sent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='cpu_perc',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='mem_perc',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
